version: "3.7"

services:
  mysql:
    image: mysql:5
    environment:
      MYSQL_DATABASE: "xpovoc"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "Test!123"
      MYSQL_RANDOM_ROOT_PASSWORD: "Y"
    ports:
    - 3306:3306

  pgsql:
    image: postgres:10
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "Test!123"
    ports:
    - 5432:5432
  
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test!123"
      MSSQL_PID: "Developer"
    ports:
    - 1433:1433

  mongo:
    image: mongo:4.4.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "Test!123"
    ports:
    - 27017:27017
